package com.fc.v2.mapper.kcgl;

import com.fc.v2.model.kcgl.CoursePart;
import com.fc.v2.model.kcgl.CoursePartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoursePartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    long countByExample(CoursePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int deleteByExample(CoursePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int insert(CoursePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int insertSelective(CoursePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    List<CoursePart> selectByExample(CoursePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    CoursePart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoursePart record, @Param("example") CoursePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoursePart record, @Param("example") CoursePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoursePart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoursePart record);
}