package com.fc.v2.model.kcgl;

import java.io.Serializable;

public class CoursePart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.partName
     *
     * @mbg.generated
     */
    private String partname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.teacherId
     *
     * @mbg.generated
     */
    private String teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.courseId
     *
     * @mbg.generated
     */
    private String courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.order
     *
     * @mbg.generated
     */
    private String order;

    private String num;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wb_course_part.videoPath
     *
     * @mbg.generated
     */
    private String videopath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.id
     *
     * @return the value of t_wb_course_part.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.id
     *
     * @param id the value for t_wb_course_part.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.partName
     *
     * @return the value of t_wb_course_part.partName
     *
     * @mbg.generated
     */
    public String getPartname() {
        return partname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.partName
     *
     * @param partname the value for t_wb_course_part.partName
     *
     * @mbg.generated
     */
    public void setPartname(String partname) {
        this.partname = partname == null ? null : partname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.teacherId
     *
     * @return the value of t_wb_course_part.teacherId
     *
     * @mbg.generated
     */
    public String getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.teacherId
     *
     * @param teacherid the value for t_wb_course_part.teacherId
     *
     * @mbg.generated
     */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid == null ? null : teacherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.courseId
     *
     * @return the value of t_wb_course_part.courseId
     *
     * @mbg.generated
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.courseId
     *
     * @param courseid the value for t_wb_course_part.courseId
     *
     * @mbg.generated
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.order
     *
     * @return the value of t_wb_course_part.order
     *
     * @mbg.generated
     */
    public String getOrder() {
        return order;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.order
     *
     * @param order the value for t_wb_course_part.order
     *
     * @mbg.generated
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wb_course_part.videoPath
     *
     * @return the value of t_wb_course_part.videoPath
     *
     * @mbg.generated
     */
    public String getVideopath() {
        return videopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wb_course_part.videoPath
     *
     * @param videopath the value for t_wb_course_part.videoPath
     *
     * @mbg.generated
     */
    public void setVideopath(String videopath) {
        this.videopath = videopath == null ? null : videopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoursePart other = (CoursePart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPartname() == null ? other.getPartname() == null : this.getPartname().equals(other.getPartname()))
            && (this.getTeacherid() == null ? other.getTeacherid() == null : this.getTeacherid().equals(other.getTeacherid()))
            && (this.getCourseid() == null ? other.getCourseid() == null : this.getCourseid().equals(other.getCourseid()))
            && (this.getOrder() == null ? other.getOrder() == null : this.getOrder().equals(other.getOrder()))
            && (this.getVideopath() == null ? other.getVideopath() == null : this.getVideopath().equals(other.getVideopath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPartname() == null) ? 0 : getPartname().hashCode());
        result = prime * result + ((getTeacherid() == null) ? 0 : getTeacherid().hashCode());
        result = prime * result + ((getCourseid() == null) ? 0 : getCourseid().hashCode());
        result = prime * result + ((getOrder() == null) ? 0 : getOrder().hashCode());
        result = prime * result + ((getVideopath() == null) ? 0 : getVideopath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wb_course_part
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", partname=").append(partname);
        sb.append(", teacherid=").append(teacherid);
        sb.append(", courseid=").append(courseid);
        sb.append(", order=").append(order);
        sb.append(", videopath=").append(videopath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}